#= require ./store
#= require_tree ./models
#= require_tree ./controllers
#= require_tree ./views
#= require_tree ./helpers
#= require_tree ./templates
#= require_tree ./managers
#= require_tree ./routes
#= require_tree ./serializers
#= require ./router
#= require ./ajax_config
#= require_self
