#= require ./store
#= require_tree ./models
#= require_tree ./controllers
#= require_tree ./views
#= require_tree ./helpers
#= require_tree ./templates
#= require_tree ./routes
#= require ./router
#= require ./ajax_config
#= require ./authentication_manager
#= require ./flash_messages_manager
#= require_self
